services:
  lyra.db:
    image: mcr.microsoft.com/mssql/server:2022-latest

  lyra.server:
    image: ${DOCKER_REGISTRY-}lyraserver
    build:
      context: .
      dockerfile: LYRA.Server/Dockerfile
  
networks:
  gloria-net:
    external: true